In [4]:
import numpy as np

In [5]:
a = np.array([10, 10])


In [6]:
b = np.array([2,2])

In [4]:
a-b

array([8, 8])

In [5]:
np.norm(a-b)

AttributeError: module 'numpy' has no attribute 'norm'

In [6]:
np.sum(a-b)

16

In [7]:
np.sum((a-b)**2)

128

In [9]:
np.sqrt(np.sum((a-b)**2))

11.313708498984761

In [10]:
np.Inf

inf

In [11]:
a=np.array([10,11])

In [31]:
len(np.where(a==20)[0].tolist())

0

In [24]:
print(z)

[0]


In [15]:
z + 2

array([2])

In [16]:
z.isempty

AttributeError: 'numpy.ndarray' object has no attribute 'isempty'

In [17]:
np.empty(z)

array([], dtype=float64)

In [18]:
z.empty()

AttributeError: 'numpy.ndarray' object has no attribute 'empty'

In [19]:
z

array([0])

In [20]:
c = np.array([])

In [21]:
c

array([], dtype=float64)

In [22]:
np.isempty(z)

AttributeError: module 'numpy' has no attribute 'isempty'

In [32]:
a

array([10, 11])

In [33]:
import random

In [37]:
random.randint(0,len(a)-1)

1

In [38]:
100 <np.Inf

True